services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=earthenhub
      - POSTGRES_USER=earthen
      - POSTGRES_PASSWORD=your_secure_password
    restart: always

  backend:
    build: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DATABASE_URL=postgres://earthen:your_secure_password@db:5432/earthenhub
      - SECRET_KEY=your_production_secret_key
      - DEBUG=False
      - ALLOWED_HOSTS=earthen.my.id,backend,localhost
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=0.0.0.0
      - BACKEND_URL=http://backend:8000
      - NEXT_SERVER_API_URL=http://backend:8000/api
      - RESEND_API_KEY=${RESEND_API_KEY}
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
