# Generated by Django 5.2.9 on 2026-05-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(help_text="e.g., '01', '02'", max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text="Lucide icon name, e.g., 'Code2'", max_length=50)),
                ('description', models.TextField()),
                ('stack', models.JSONField(default=list, help_text='List of strings representing technologies')),
                ('accent_color', models.CharField(help_text="Hex code, e.g., '#6ee7b7'", max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('education', 'Education'), ('work', 'Work'), ('achievement', 'Achievement'), ('project', 'Project')], max_length=20)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('responded', 'Responded'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Philosophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Earthen', max_length=100)),
                ('professional_titles', models.CharField(help_text='Comma-separated titles', max_length=200)),
                ('philosophy_text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Philosophies',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('dev', 'Development'), ('infra', 'Infrastructure'), ('design', 'Design'), ('hardware', 'Hardware')], max_length=20)),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('description', models.TextField()),
                ('proficiency', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20, null=True)),
                ('specifications', models.CharField(blank=True, help_text='e.g., Ryzen 7 8840HS', max_length=200, null=True)),
                ('frame_count', models.PositiveIntegerField(blank=True, help_text='For cameras only', null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhilosophyTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('philosophy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='earthenhub.philosophy')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('challenge', models.TextField()),
                ('approach', models.TextField()),
                ('outcome_metrics', models.JSONField(default=list, help_text="List of strings, e.g., ['99.9% uptime', '300ms avg response']")),
                ('technology_tags', models.JSONField(default=list, help_text='List of strings representing tech stack')),
                ('image_url', models.URLField(blank=True, help_text='URL to the project image', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='earthenhub.discipline')),
            ],
            options={
                'ordering': ['sort_order', '-id'],
            },
        ),
    ]
