# Generated by Django 5.2.9 on 2026-05-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthenhub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='philosophy',
            name='professional_titles',
        ),
    ]
