# Generated by Django 5.2.9 on 2026-05-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthenhub', '0002_remove_philosophy_professional_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='proficiency',
            field=models.CharField(blank=True, choices=[('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20, null=True),
        ),
    ]
