# Generated by Django 5.2.9 on 2026-05-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthenhub', '0003_alter_tool_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link to the external website for this project', null=True),
        ),
    ]
