# Generated by Django 5.2.9 on 2026-05-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthenhub', '0004_project_external_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text="Unique string key (e.g., 'aws-solutions-architect')", null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('image_url', models.URLField(blank=True, help_text='URL to certificate image', null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
