# Generated by Django 5.2.9 on 2026-05-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthenhub', '0005_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
    ]
